# Demostración de Funciones del Módulo utils.py

Este notebook demuestra el funcionamiento de todas las funciones disponibles en el archivo `utils.py` del proyecto de análisis de rendimiento deportivo.

## Estructura del Módulo

El módulo está organizado en las siguientes secciones:
1. **Configuración de Rutas**
2. **Carga y Filtrado de Datos**
3. **Procesamiento de Métricas**
4. **Manejo de Fechas**
5. **Funciones Auxiliares**
6. **Cálculo de Estadísticas Comparativas**
7. **Análisis Comparativo con Datos Históricos**

In [2]:
# Importar las librerías necesarias
import sys
import os

# Añadir el directorio utils al path
sys.path.append(os.path.join(os.getcwd(), 'utils'))

# Importar todas las funciones del módulo utils
from utils import *

print("Módulo utils importado correctamente")

Módulo utils importado correctamente

## 1. Configuración de Rutas del Proyecto

Estas variables definen las rutas principales del proyecto.

In [3]:
# Mostrar las rutas configuradas
print("=== CONFIGURACIÓN DE RUTAS ===")
print(f"Ruta base del proyecto: {BASE_PATH}")
print(f"Ruta de datos GPS: {DATA_GPS_PATH}")
print(f"Ruta de datos procesados: {DATA_PROCESSED_PATH}")

=== CONFIGURACIÓN DE RUTAS ===
Ruta base del proyecto: c:\Users\ricar\Desktop\SDC\MIAD\Extensión_Profesional\performanceApp
Ruta de datos GPS: c:\Users\ricar\Desktop\SDC\MIAD\Extensión_Profesional\performanceApp\data\gps
Ruta de datos procesados: c:\Users\ricar\Desktop\SDC\MIAD\Extensión_Profesional\performanceApp\data\processed

## 2. Funciones de Carga y Filtrado de Datos

### 2.1 load_gps_data()
Carga los datos GPS desde el archivo parquet principal.

In [4]:
# Cargar datos GPS
df_gps = load_gps_data()

if df_gps is not None:
    print(f"Datos GPS cargados exitosamente")
    print(f"Dimensiones: {df_gps.shape}")
    print(f"Columnas disponibles: {len(df_gps.columns)}")
    print(f"Primeras 5 columnas: {df_gps.columns[:5]}")
else:
    print("No se pudieron cargar los datos GPS")
    
df_gps.head()

Datos GPS cargados exitosamente
Dimensiones: (18096, 253)
Columnas disponibles: 253
Primeras 5 columnas: ['Player', 'Nick Name', 'Team ', 'Position', 'Sport']

shape: (5, 253)
┌────────────┬───────────┬────────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ Player     ┆ Nick Name ┆ Team       ┆ Position  ┆ … ┆ Max Accel ┆ Speed of  ┆ SIGNAL ┆ File Name │
│ ---        ┆ ---       ┆ ---        ┆ ---       ┆   ┆ eration   ┆ Max Accel ┆ ---    ┆ ---       │
│ str        ┆ str       ┆ str        ┆ str       ┆   ┆ ---       ┆ eration   ┆ str    ┆ str       │
│            ┆           ┆            ┆           ┆   ┆ f64       ┆ ---       ┆        ┆           │
│            ┆           ┆            ┆           ┆   ┆           ┆ f64       ┆        ┆           │
╞════════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ Uros       ┆ Uros      ┆ Sporting   ┆ Delantero ┆ … ┆ 4.798969  ┆ 3.007667  ┆ GPS    ┆ 03_07_202 │
│ Djurdjevic ┆           ┆ de Gijón   ┆           ┆   ┆           ┆           ┆        ┆ 3_al_31_0 │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ 8_2023.xl │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ sx        │
│ Cali       ┆ Cali      ┆ Sporting   ┆ Central   ┆ … ┆ 4.617946  ┆ 3.355667  ┆ GPS    ┆ 03_07_202 │
│ Izquierdoz ┆           ┆ de Gijón   ┆           ┆   ┆           ┆           ┆        ┆ 3_al_31_0 │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ 8_2023.xl │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ sx        │
│ Yann Kembo ┆ Yann      ┆ Sporting   ┆ 0         ┆ … ┆ 4.734722  ┆ 3.1635    ┆ GPS    ┆ 03_07_202 │
│            ┆           ┆ Atlético   ┆           ┆   ┆           ┆           ┆        ┆ 3_al_31_0 │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ 8_2023.xl │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ sx        │
│ Diego      ┆ Diego     ┆ Sporting   ┆ Lateral   ┆ … ┆ 4.580484  ┆ 3.24      ┆ GPS    ┆ 03_07_202 │
│ Sánchez    ┆           ┆ de Gijón   ┆           ┆   ┆           ┆           ┆        ┆ 3_al_31_0 │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ 8_2023.xl │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ sx        │
│ Pedro Díaz ┆ Pedro     ┆ Sporting   ┆ Centrocam ┆ … ┆ 4.457155  ┆ 3.680667  ┆ GPS    ┆ 03_07_202 │
│            ┆           ┆ de Gijón   ┆ pista     ┆   ┆           ┆           ┆        ┆ 3_al_31_0 │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ 8_2023.xl │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ sx        │
└────────────┴───────────┴────────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

### 2.2 get_columns_of_interest()
Carga las columnas de interés desde el archivo de configuración.

In [5]:
# Obtener columnas de interés
columnas_interes = get_columns_of_interest()

print(f"Número de columnas de interés: {len(columnas_interes)}")
print("Columnas de interés:")
for i, col in enumerate(columnas_interes):  # Mostrar solo las primeras 10
    print(f"  {i}. {col}")

Número de columnas de interés: 14
Columnas de interés:
  0. Distance (m)
  1. Speed Zones (m) [0.0, 6.0]km/h (m)
  2. Abs HSR(m)
  3. Rel HSR(m)
  4. Sprint Abs (m)
  5. Sprint Rel (m)
  6. Explosive Dist (m)
  7. MAX Speed(km/h) ?
  8. Max Acceleration
  9. Accelerations
  10. Decelerations
  11. Dif. ACC/DEC
  12. Step Balance (%)
  13. Total impacts

### 2.3 apply_standard_filters(df)
Aplica filtros estándar a los datos GPS para limpiar y preparar los datos.

In [6]:
if df_gps is not None:
    print("=== ANTES DE APLICAR FILTROS ===")
    print(f"Filas totales: {df_gps.height}")
    
    # Mostrar valores únicos de columnas clave antes del filtrado
    if 'Match Day' in df_gps.columns:
        match_days_antes = df_gps['Match Day'].unique().to_list()
        print(f"Match Days únicos: {match_days_antes}")
    
    # Aplicar filtros estándar
    df_filtrado = apply_standard_filters(df_gps)
    
    print("\n=== DESPUÉS DE APLICAR FILTROS ===")
    print(f"Filas después del filtrado: {df_filtrado.height}")
    print(f"Filas eliminadas: {df_gps.height - df_filtrado.height}")
    
    if 'Match Day' in df_filtrado.columns:
        match_days_despues = df_filtrado['Match Day'].unique().to_list()
        print(f"Match Days después del filtrado: {match_days_despues}")
else:
    print("No hay datos GPS para filtrar")

=== ANTES DE APLICAR FILTROS ===
Filas totales: 18096
Match Days únicos: ['>-5 MD', '-4 MD', '+2 MD', '-3 MD', 'Rehab', 'MD', '+1 MD', '-2 MD', '-1 MD', 'No MD', '-5 MD']

=== DESPUÉS DE APLICAR FILTROS ===
Filas después del filtrado: 2015
Filas eliminadas: 16081
Match Days después del filtrado: ['-5 MD', '+1 MD', '>-5 MD', '+2 MD', 'MD', '-4 MD', '-3 MD', 'No MD', '-1 MD', '-2 MD']

## 3. Funciones de Procesamiento de Métricas

### 3.1 add_per_minute_metrics(df, session_minutes)
Calcula y añade métricas por minuto al DataFrame.

In [7]:
if df_gps is not None:
    # Tomar una pequeña muestra para demostración
    df_muestra = df_gps.head(5)
    
    # Verificar si existen las columnas requeridas
    columnas_metricas = ['Explosive Dist (m)', 'Abs HSR(m)', 'Distance (m)']
    columnas_existentes = [col for col in columnas_metricas if col in df_muestra.columns]
    
    # Aplicar métricas por minuto con duración de ejemplo
    session_minutes_ejemplo = "01:30:00"  # 90 minutos
    print(f"\nDuración de la sesión: {session_minutes_ejemplo}")
    df_con_metricas, columnas_actualizadas = add_per_minute_metrics(df_muestra, session_minutes_ejemplo)
    
    # Seleccionar columnas para mostrar
    columns_to_show = ['Player'] + columnas_metricas + [col for col in df_con_metricas.columns if '/min' in col or '/Min' in col]
    
    # Mostrar DataFrame con las columnas seleccionadas
    print("\nDataFrame con métricas originales y por minuto:")
    print(df_con_metricas[columns_to_show])
else:
    print("No hay datos GPS disponibles para procesar métricas")

Duración de la sesión: 01:30:00

DataFrame con métricas originales y por minuto:
shape: (5, 7)
┌──────────────┬──────────────┬────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ Player       ┆ Explosive    ┆ Abs HSR(m) ┆ Distance    ┆ Explosive   ┆ Abs         ┆ Distance    │
│ ---          ┆ Dist (m)     ┆ ---        ┆ (m)         ┆ Dist        ┆ HSR(m)/Min  ┆ (m)/min     │
│ str          ┆ ---          ┆ f64        ┆ ---         ┆ (m)/min     ┆ ---         ┆ ---         │
│              ┆ f64          ┆            ┆ f64         ┆ ---         ┆ f64         ┆ f64         │
│              ┆              ┆            ┆             ┆ f64         ┆             ┆             │
╞══════════════╪══════════════╪════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ Uros         ┆ 441.984462   ┆ 61.813406  ┆ 5966.957182 ┆ 4.910938    ┆ 0.686816    ┆ 66.299524   │
│ Djurdjevic   ┆              ┆            ┆             ┆             ┆             ┆             │
│ Cali         ┆ 561.716173   ┆ 41.913813  ┆ 5892.944123 ┆ 6.241291    ┆ 0.465709    ┆ 65.477157   │
│ Izquierdoz   ┆              ┆            ┆             ┆             ┆             ┆             │
│ Yann Kembo   ┆ 642.325524   ┆ 150.641345 ┆ 5935.982976 ┆ 7.13695     ┆ 1.673793    ┆ 65.955366   │
│ Diego        ┆ 633.649315   ┆ 141.916989 ┆ 6142.893404 ┆ 7.040548    ┆ 1.576855    ┆ 68.254371   │
│ Sánchez      ┆              ┆            ┆             ┆             ┆             ┆             │
│ Pedro Díaz   ┆ 581.682111   ┆ 131.968731 ┆ 6375.36505  ┆ 6.463135    ┆ 1.466319    ┆ 70.837389   │
└──────────────┴──────────────┴────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

## 4. Funciones de Manejo de Fechas

### 4.1 get_sorted_dates()
Obtiene todas las fechas disponibles en los datos GPS ordenadas cronológicamente.

In [8]:
# Obtener fechas ordenadas
fechas_ordenadas = get_sorted_dates()

print(f"Total de fechas disponibles: {len(fechas_ordenadas)}")
if fechas_ordenadas:
    print(f"Primera fecha: {fechas_ordenadas[0]}")
    print(f"Última fecha: {fechas_ordenadas[-1]}")
    print("\nPrimeras 5 fechas:")
    for fecha in fechas_ordenadas[:5]:
        print(f"  - {fecha}")
    if len(fechas_ordenadas) > 5:
        print("\nÚltimas 5 fechas:")
        for fecha in fechas_ordenadas[-5:]:
            print(f"  - {fecha}")
else:
    print("No se encontraron fechas en los datos")

Total de fechas disponibles: 95
Primera fecha: 05/07/2023
Última fecha: 31/12/2023

Primeras 5 fechas:
  - 05/07/2023
  - 06/07/2023
  - 07/07/2023
  - 08/07/2023
  - 10/07/2023

Últimas 5 fechas:
  - 19/12/2023
  - 20/12/2023
  - 29/12/2023
  - 30/12/2023
  - 31/12/2023

### 4.2 get_latest_date_for_picker()
Obtiene la fecha más reciente en formato compatible con DatePickerSingle.

In [9]:
# Obtener fecha más reciente para picker
fecha_picker = get_latest_date_for_picker()

if fecha_picker:
    print(f"Fecha más reciente (formato picker): {fecha_picker}")
    print(f"Formato: YYYY-MM-DD (compatible con DatePickerSingle)")
else:
    print("No se pudo obtener la fecha más reciente")

Fecha más reciente (formato picker): 2023-12-31
Formato: YYYY-MM-DD (compatible con DatePickerSingle)

### 4.3 format_and_filter_date(selected_date)
Formatea una fecha seleccionada y filtra los datos GPS para esa fecha específica.

In [10]:
# Usar la fecha más reciente como ejemplo
if fecha_picker:
    print(f"Filtrando datos para la fecha: {fecha_picker}")
    
    df_fecha, fecha_formateada = format_and_filter_date(fecha_picker)
    
    if df_fecha is not None:
        print(f"Fecha formateada: {fecha_formateada}")
        print(f"Registros encontrados: {df_fecha.height}")
        print(f"Columnas disponibles: {len(df_fecha.columns)}")
        
        # Mostrar información básica de los datos filtrados
        if 'Player' in df_fecha.columns:
            jugadores_unicos = df_fecha['Player'].unique().to_list()
            print(f"Jugadores únicos en esta fecha: {len(jugadores_unicos)}")
        
        if 'Match Day' in df_fecha.columns:
            match_days = df_fecha['Match Day'].unique().to_list()
            print(f"Match Days en esta fecha: {match_days}")
    else:
        print("No se encontraron datos para esta fecha")
else:
    print("No hay fecha disponible para filtrar")
    
df_fecha.head()

Filtrando datos para la fecha: 2023-12-31
Fecha formateada: 31/12/2023
Registros encontrados: 25
Columnas disponibles: 253
Jugadores únicos en esta fecha: 25
Match Days en esta fecha: ['No MD']

shape: (5, 253)
┌────────────┬───────────┬────────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ Player     ┆ Nick Name ┆ Team       ┆ Position  ┆ … ┆ Max Accel ┆ Speed of  ┆ SIGNAL ┆ File Name │
│ ---        ┆ ---       ┆ ---        ┆ ---       ┆   ┆ eration   ┆ Max Accel ┆ ---    ┆ ---       │
│ str        ┆ str       ┆ str        ┆ str       ┆   ┆ ---       ┆ eration   ┆ str    ┆ str       │
│            ┆           ┆            ┆           ┆   ┆ f64       ┆ ---       ┆        ┆           │
│            ┆           ┆            ┆           ┆   ┆           ┆ f64       ┆        ┆           │
╞════════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ Haissem    ┆ Haissem   ┆ Sporting   ┆ Delantero ┆ … ┆ 4.670265  ┆ 3.277     ┆ GPS    ┆ 01_11_202 │
│ Hassan     ┆           ┆ de Gijón   ┆           ┆   ┆           ┆           ┆        ┆ 3_al_31_1 │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ 2_2023.xl │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ sx        │
│ Jordan     ┆ Jordan    ┆ Sporting   ┆ Centrocam ┆ … ┆ 4.512992  ┆ 3.209     ┆ GPS    ┆ 01_11_202 │
│ Carrillo   ┆           ┆ de Gijón   ┆ pista     ┆   ┆           ┆           ┆        ┆ 3_al_31_1 │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ 2_2023.xl │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ sx        │
│ Jonathan   ┆ Jonathan  ┆ Sporting   ┆ Central   ┆ … ┆ 4.122096  ┆ 3.258333  ┆ GPS    ┆ 01_11_202 │
│ Varane     ┆           ┆ de Gijón   ┆           ┆   ┆           ┆           ┆        ┆ 3_al_31_1 │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ 2_2023.xl │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ sx        │
│ Nacho      ┆ Nacho     ┆ Sporting   ┆ Centrocam ┆ … ┆ 4.551528  ┆ 3.305     ┆ GPS    ┆ 01_11_202 │
│ Martín     ┆           ┆ de Gijón   ┆ pista     ┆   ┆           ┆           ┆        ┆ 3_al_31_1 │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ 2_2023.xl │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ sx        │
│ Fran       ┆ Fran      ┆ Sporting   ┆ Extremo   ┆ … ┆ 4.208018  ┆ 3.181833  ┆ GPS    ┆ 01_11_202 │
│ Villalba   ┆           ┆ de Gijón   ┆           ┆   ┆           ┆           ┆        ┆ 3_al_31_1 │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ 2_2023.xl │
│            ┆           ┆            ┆           ┆   ┆           ┆           ┆        ┆ sx        │
└────────────┴───────────┴────────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

### 4.4 filter_and_get_players_data(selected_date)
Filtra y procesa los datos GPS de jugadores para una fecha específica.

In [11]:
# Obtener datos procesados de jugadores para una fecha específica
if fecha_picker:
    print(f"Obteniendo datos procesados de jugadores para: {fecha_picker}")
    
    df_jugadores = filter_and_get_players_data(fecha_picker)
    
    if df_jugadores is not None:
        print(f"Datos de jugadores obtenidos exitosamente")
        print(f"Dimensiones: {df_jugadores.shape}")
        print(f"Columnas incluidas: {df_jugadores.columns}")
        
        # Mostrar una muestra de los datos
        print("\nMuestra de datos ")
        print(df_jugadores.head())
    else:
        print("No se pudieron obtener datos de jugadores para esta fecha")
else:
    print("No hay fecha disponible para procesar")

Obteniendo datos procesados de jugadores para: 2023-12-31
Datos de jugadores obtenidos exitosamente
Dimensiones: (25, 16)
Columnas incluidas: ['Player', 'Abs HSR(m)', 'Abs HSR(m)/Min', 'Accelerations', 'Decelerations', 'Dif. ACC/DEC', 'Distance (m)', 'Distance (m)/min', 'Explosive Dist (m)', 'Explosive Dist (m)/min', 'Max Acceleration', 'Speed Zones (m) [0.0, 6.0]km/h (m)', 'Sprint Abs (m)', 'Sprint Rel (m)', 'Step Balance (%)', 'Total impacts']

Muestra de datos
shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Player    ┆ Abs       ┆ Abs HSR(m ┆ Accelerat ┆ … ┆ Sprint    ┆ Sprint    ┆ Step      ┆ Total    │
│ ---       ┆ HSR(m)    ┆ )/Min     ┆ ions      ┆   ┆ Abs (m)   ┆ Rel (m)   ┆ Balance   ┆ impacts  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ (%)       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Haissem   ┆ 109.80092 ┆ 2.363852  ┆ 1404.0    ┆ … ┆ 9.426568  ┆ 0.0       ┆ 0.00531   ┆ 7733.0   │
│ Hassan    ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Jordan    ┆ 44.038804 ┆ 0.948091  ┆ 1398.0    ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.020871 ┆ 7308.0   │
│ Carrillo  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Jonathan  ┆ 56.706164 ┆ 1.2208    ┆ 1313.0    ┆ … ┆ 8.539757  ┆ 0.0       ┆ 0.013125  ┆ 8734.0   │
│ Varane    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Nacho     ┆ 135.00603 ┆ 2.906481  ┆ 1390.0    ┆ … ┆ 18.939522 ┆ 0.0       ┆ 0.040835  ┆ 8305.0   │
│ Martín    ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Fran      ┆ 188.53577 ┆ 4.058897  ┆ 1342.0    ┆ … ┆ 40.157474 ┆ 0.0       ┆ 0.031614  ┆ 8018.0   │
│ Villalba  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 6. Funciones de Cálculo de Estadísticas Comparativas

### 6.1 calcular_estadisticas(fecha=None, columnas_interes=None, estadistica=None)
Calcula estadísticas comparativas para jugadores, posiciones y equipos por Match Day.

In [12]:
# Calcular estadísticas generales (sin fecha específica)
print("=== CALCULANDO ESTADÍSTICAS GENERALES ===")
print("Esto puede tomar unos momentos...")

df_jugadores_stats, df_posiciones_stats, df_equipos_stats = calcular_estadisticas_por_matchday()
    
df_jugadores_stats.head()

=== CALCULANDO ESTADÍSTICAS GENERALES ===
Esto puede tomar unos momentos...
Estadísticas generales guardadas con nomenclatura estándar

shape: (5, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Player    ┆ Position  ┆ Match Day ┆ Estadisti ┆ … ┆ Sprint    ┆ Sprint    ┆ Step      ┆ Total    │
│ ---       ┆ ---       ┆ ---       ┆ ca        ┆   ┆ Abs (m)   ┆ Rel (m)   ┆ Balance   ┆ impacts  │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ (%)       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Daniel    ┆ Centrocam ┆ >-5 MD    ┆ mean      ┆ … ┆ 31.77042  ┆ 0.0       ┆ -0.006358 ┆ 9423.0   │
│ Queipo    ┆ pista     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Daniel    ┆ Centrocam ┆ >-5 MD    ┆ median    ┆ … ┆ 31.77042  ┆ 0.0       ┆ -0.006358 ┆ 9423.0   │
│ Queipo    ┆ pista     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Daniel    ┆ Centrocam ┆ >-5 MD    ┆ max       ┆ … ┆ 31.77042  ┆ 0.0       ┆ -0.006358 ┆ 9423.0   │
│ Queipo    ┆ pista     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Daniel    ┆ Centrocam ┆ >-5 MD    ┆ min       ┆ … ┆ 31.77042  ┆ 0.0       ┆ -0.006358 ┆ 9423.0   │
│ Queipo    ┆ pista     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Daniel    ┆ Centrocam ┆ >-5 MD    ┆ p75       ┆ … ┆ 31.77042  ┆ 0.0       ┆ -0.006358 ┆ 9423.0   │
│ Queipo    ┆ pista     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
# Calcular estadísticas para una fecha específica
print("\n=== CALCULANDO ESTADÍSTICAS PARA FECHA ESPECÍFICA ===")

# Obtener una fecha disponible de los datos
if df_gps is not None and 'Date' in df_gps.columns:
    fechas_disponibles = df_gps['Date'].unique().sort()
    if len(fechas_disponibles) > 0:
        fecha_ejemplo = fechas_disponibles[-1]  # Usar la última fecha disponible
        print(f"Calculando estadísticas para la fecha: {fecha_ejemplo}")
        
        # Calcular estadísticas para la fecha específica
        df_jugadores_fecha, df_posiciones_fecha, df_equipos_fecha = calcular_estadisticas(
            fecha=fecha_ejemplo,
            columnas_interes=None,
            estadistica= None # Solo calcular media para acelerar
        )
        
        print(f"\nResultados para jugadores en fecha {fecha_ejemplo}:")
        print(f"Número de registros: {df_jugadores_fecha.height if df_jugadores_fecha is not None else 0}")
        
        if df_jugadores_fecha is not None and df_jugadores_fecha.height > 0:
            print("\nPrimeras filas:")
            display(df_jugadores_fecha.head(50))
        else:
            print("No hay datos para la fecha especificada")
    else:
        print("No hay fechas disponibles en los datos")
else:
    print("No hay datos GPS o columna Date disponible")

=== CALCULANDO ESTADÍSTICAS PARA FECHA ESPECÍFICA ===
Calculando estadísticas para la fecha: 31/12/2023

Resultados para jugadores en fecha 31/12/2023:
Número de registros: 385

Primeras filas:

shape: (50, 19)
┌────────────┬────────────┬───────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Player     ┆ Position   ┆ Match ┆ Estadistic ┆ … ┆ Sprint    ┆ Sprint    ┆ Step      ┆ Total     │
│ ---        ┆ ---        ┆ Day   ┆ a          ┆   ┆ Abs (m)   ┆ Rel (m)   ┆ Balance   ┆ impacts   │
│ str        ┆ str        ┆ ---   ┆ ---        ┆   ┆ ---       ┆ ---       ┆ (%)       ┆ ---       │
│            ┆            ┆ str   ┆ str        ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64       │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ f64       ┆           │
╞════════════╪════════════╪═══════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Alexandru  ┆ Central    ┆ No MD ┆ mean       ┆ … ┆ 7.911636  ┆ 0.0       ┆ -0.018401 ┆ 10107.0   │
│ Pascanu    ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ Alexandru  ┆ Central    ┆ No MD ┆ median     ┆ … ┆ 7.911636  ┆ 0.0       ┆ -0.018401 ┆ 10107.0   │
│ Pascanu    ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ Alexandru  ┆ Central    ┆ No MD ┆ max        ┆ … ┆ 7.911636  ┆ 0.0       ┆ -0.018401 ┆ 10107.0   │
│ Pascanu    ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ Alexandru  ┆ Central    ┆ No MD ┆ min        ┆ … ┆ 7.911636  ┆ 0.0       ┆ -0.018401 ┆ 10107.0   │
│ Pascanu    ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ Alexandru  ┆ Central    ┆ No MD ┆ p75        ┆ … ┆ 7.911636  ┆ 0.0       ┆ -0.018401 ┆ 10107.0   │
│ Pascanu    ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …     ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Nacho      ┆ Centrocamp ┆ No MD ┆ min        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.048401  ┆ 9317.0    │
│ Méndez     ┆ ista       ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ Nacho      ┆ Centrocamp ┆ No MD ┆ p75        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.048401  ┆ 9317.0    │
│ Méndez     ┆ ista       ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ Nacho      ┆ Centrocamp ┆ No MD ┆ p90        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.048401  ┆ 9317.0    │
│ Méndez     ┆ ista       ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ Nacho      ┆ Centrocamp ┆ No MD ┆ p95        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.048401  ┆ 9317.0    │
│ Méndez     ┆ ista       ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ Nacho      ┆ Centrocamp ┆ MD    ┆ mean       ┆ … ┆ 69.804365 ┆ 0.0       ┆ 0.025501  ┆ 27170.0   │
│ Méndez     ┆ ista       ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴───────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

### 6.3 calcular_metricas(df, columnas, estadistica)
Función auxiliar para calcular estadísticas específicas sobre columnas dadas.

In [14]:
# Demostrar calcular_metricas con una muestra de datos
if df_gps is not None:
    # Tomar una muestra pequeña
    df_muestra = df_gps
    
    # Columnas de ejemplo para calcular métricas
    columnas_ejemplo = ['Distance (m)', 'Max Speed (km/h)']
    columnas_disponibles = [col for col in columnas_ejemplo if col in df_muestra.columns]
    
    if columnas_disponibles:
        print(f"Calculando métricas para columnas: {columnas_disponibles}")
        
        # Calcular diferentes estadísticas
        estadisticas_ejemplo = ['mean', 'median', 'max', 'min']
        
        for estadistica in estadisticas_ejemplo:
            resultado = calcular_metricas(df_muestra, columnas_disponibles, estadistica)
            print(f"\n{estadistica.upper()}:")
            for columna, valor in resultado.items():
                print(f"  {columna}: {valor:.2f}" if valor is not None else f"  {columna}: None")
    else:
        print("No hay columnas disponibles para calcular métricas")
else:
    print("No hay datos GPS para calcular métricas")

Calculando métricas para columnas: ['Distance (m)']

MEAN:
  Distance (m): 1798.44

MEDIAN:
  Distance (m): 773.90

MAX:
  Distance (m): 17252.01

MIN:
  Distance (m): 0.00

### 6.4 calcular_diferencia_porcentual(df)
Calcula diferencias porcentuales entre Match Days no-MD y MD de referencia.

In [15]:
# Demostrar calcular_diferencia_porcentual
if df_jugadores_stats is not None and df_jugadores_stats.height > 0:
    
    # Mostrar filas con diferencias porcentuales (ahora incluyen el Match Day específico)
    df_diferencias = df_jugadores_stats.filter(pl.col('Match Day').str.contains('diferencia'))
    if df_diferencias.height > 0:
        print(f"\nFilas con diferencias porcentuales: {df_diferencias.height}")
        
        # Mostrar los diferentes tipos de diferencias calculadas
        match_days_diferencia = df_diferencias['Match Day'].unique().to_list()
        print(f"\nTipos de diferencias calculadas: {match_days_diferencia}")
        
        print("\nMuestra de diferencias (primeras filas):")
        print(df_diferencias.head(5))
        
else:
    print("No hay datos de estadísticas para calcular diferencias porcentuales")

Filas con diferencias porcentuales: 1554

Tipos de diferencias calculadas: ['diferencia No MD', 'diferencia -1 MD', 'diferencia +2 MD', 'diferencia >-5 MD', 'diferencia +1 MD', 'diferencia -4 MD', 'diferencia -2 MD', 'diferencia -3 MD', 'diferencia -5 MD']

Muestra de diferencias (primeras filas):
shape: (5, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Player    ┆ Position  ┆ Match Day ┆ Estadisti ┆ … ┆ Sprint    ┆ Sprint    ┆ Step      ┆ Total    │
│ ---       ┆ ---       ┆ ---       ┆ ca        ┆   ┆ Abs (m)   ┆ Rel (m)   ┆ Balance   ┆ impacts  │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ (%)       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Ignacio   ┆ Delantero ┆ diferenci ┆ max       ┆ … ┆ 10.93     ┆ 0.0       ┆ 264.47    ┆ 70.62    │
│ Jeraldino ┆           ┆ a >-5 MD  ┆           ┆   ┆           ┆           ┆           ┆          │
│ Ignacio   ┆ Delantero ┆ diferenci ┆ max       ┆ … ┆ 96.08     ┆ 0.0       ┆ 163.24    ┆ 106.27   │
│ Jeraldino ┆           ┆ a -4 MD   ┆           ┆   ┆           ┆           ┆           ┆          │
│ Ignacio   ┆ Delantero ┆ diferenci ┆ max       ┆ … ┆ 26.29     ┆ 0.0       ┆ 130.79    ┆ 13.01    │
│ Jeraldino ┆           ┆ a -5 MD   ┆           ┆   ┆           ┆           ┆           ┆          │
│ Ignacio   ┆ Delantero ┆ diferenci ┆ max       ┆ … ┆ 52.16     ┆ 70.55     ┆ 218.89    ┆ 93.93    │
│ Jeraldino ┆           ┆ a -3 MD   ┆           ┆   ┆           ┆           ┆           ┆          │
│ Ignacio   ┆ Delantero ┆ diferenci ┆ max       ┆ … ┆ 17.41     ┆ 0.0       ┆ 175.32    ┆ 59.93    │
│ Jeraldino ┆           ┆ a -2 MD   ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 7. Funciones de Análisis Comparativo con Datos Históricos

### 7.1 get_historical_md_data(match_day_target, exclude_date=None)
Obtiene datos acumulados para un Match Day específico.

In [16]:
# Obtener datos históricos para un Match Day específico
if df_gps is not None and 'Match Day' in df_gps.columns:
    # Obtener Match Days disponibles
    match_days_disponibles = df_gps['Match Day'].unique().to_list()
    print(f"Match Days disponibles: {match_days_disponibles}")
    
    # Usar el primer Match Day disponible como ejemplo
    if match_days_disponibles:
        match_day_ejemplo = match_days_disponibles[3]
        print(f"\nObteniendo datos históricos para: {match_day_ejemplo}")
        
        df_historico = get_historical_md_data(match_day_ejemplo)
        
        if df_historico is not None:
            print(f"Datos históricos obtenidos: {df_historico.height} registros")
            
            # Mostrar fechas únicas en los datos históricos
            if 'Date' in df_historico.columns:
                fechas_historicas = df_historico['Date'].unique().to_list()
                print(f"Fechas en datos históricos: {len(fechas_historicas)}")
                print(f"Primeras 3 fechas: {fechas_historicas[:3]}")
        else:
            print("No se encontraron datos históricos")
    else:
        print("No hay Match Days disponibles")
else:
    print("No hay datos GPS o columna Match Day para obtener datos históricos")

Match Days disponibles: ['>-5 MD', '-5 MD', '+1 MD', '+2 MD', '-2 MD', 'MD', '-3 MD', '-4 MD', '-1 MD', 'Rehab', 'No MD']

Obteniendo datos históricos para: +2 MD
Datos históricos obtenidos: 74 registros
Fechas en datos históricos: 4
Primeras 3 fechas: ['29/08/2023', '29/11/2023', '13/08/2023']

### 7.2 calcular_comparacion_fecha_md(df_fecha, estadistica_seleccionada, columnas_interes=None)
Calcula diferencias porcentuales y z-scores comparando datos de una fecha específica con el historial del mismo Match Day.

In [17]:
# Demostrar análisis comparativo con datos históricos
if fecha_picker and df_fecha is not None:
    print(f"=== ANÁLISIS COMPARATIVO PARA FECHA: {fecha_picker} ===")
    
    # Usar solo algunas columnas para acelerar el ejemplo
    columnas_ejemplo = ['Distance (m)', 'Max Speed (km/h)']
    
    resultados_comparacion = calcular_comparacion_fecha_md(
        df_fecha, 
        estadistica_seleccionada='mean',
        columnas_interes=columnas_ejemplo
    )
    
    if resultados_comparacion:
        print(f"Análisis completado para {len(resultados_comparacion)} entidades")
        
        # Mostrar resultados para la primera entidad
        primera_entidad = list(resultados_comparacion.keys())[0]
        resultado_ejemplo = resultados_comparacion[primera_entidad]
        
        print(f"\nEjemplo de resultados para: {primera_entidad}")
        print(f"Tipo: {resultado_ejemplo.get('Player', resultado_ejemplo.get('Team', resultado_ejemplo.get('Position', 'Desconocido')))}")
        print(f"Match Day: {resultado_ejemplo.get('Match_Day')}")
        print(f"Fecha: {resultado_ejemplo.get('Date')}")
        
        print("\nDiferencias porcentuales:")
        for metrica, valor in resultado_ejemplo.get('diferencias_porcentuales', {}).items():
            print(f"  {metrica}: {valor}%" if valor is not None else f"  {metrica}: N/A")
        
        print("\nZ-scores:")
        for metrica, valor in resultado_ejemplo.get('z_scores', {}).items():
            print(f"  {metrica}: {valor}" if valor is not None else f"  {metrica}: N/A")
    else:
        print("No se pudieron calcular comparaciones")
else:
    print("No hay datos de fecha disponibles para análisis comparativo")

=== ANÁLISIS COMPARATIVO PARA FECHA: 2023-12-31 ===
Detectado: Datos de jugadores individuales
Obteniendo datos históricos para Match Day: No MD
Encontrados 718 registros históricos para Match Day: No MD
Análisis completado para 25 entidades

Ejemplo de resultados para: Roberto Suárez Pier
Tipo: Roberto Suárez Pier
Match Day: No MD
Fecha: 31/12/2023

Diferencias porcentuales:
  Abs HSR(m): -86.65%
  Abs HSR(m)/Min: -86.65%
  Accelerations: -28.52%
  Decelerations: -28.88%
  Dif. ACC/DEC: 118.18%
  Distance (m): -7.31%
  Distance (m)/min: -7.31%
  Explosive Dist (m): 27.42%
  Explosive Dist (m)/min: 27.42%
  Max Acceleration: -2.59%
  Speed Zones (m) [0.0, 6.0]km/h (m): -11.32%
  Sprint Abs (m): -100.0%
  Sprint Rel (m): -100.0%
  Step Balance (%): -159.17%
  Total impacts: 13.96%

Z-scores:
  Abs HSR(m): -0.8
  Abs HSR(m)/Min: -0.8
  Accelerations: -1.29
  Decelerations: -1.31
  Dif. ACC/DEC: 0.6
  Distance (m): -0.18
  Distance (m)/min: -0.18
  Explosive Dist (m): 0.69
  Explosive Dist (m)/min: 0.69
  Max Acceleration: -0.2
  Speed Zones (m) [0.0, 6.0]km/h (m): -0.38
  Sprint Abs (m): -0.73
  Sprint Rel (m): -0.35
  Step Balance (%): -0.58
  Total impacts: 0.38

### 7.3 Funciones auxiliares de procesamiento
Estas funciones procesan datos específicos por tipo de entidad.

In [18]:
# Las funciones _procesar_datos_jugadores, _procesar_datos_equipo, _procesar_datos_posicion
# y _calcular_metricas_entidad son funciones auxiliares internas que se utilizan
# automáticamente por calcular_comparacion_fecha_md()

print("=== FUNCIONES AUXILIARES DE PROCESAMIENTO ===")
print("Las siguientes funciones son auxiliares internas:")
print("1. _procesar_datos_jugadores() - Procesa datos de jugadores individuales")
print("2. _procesar_datos_equipo() - Procesa datos de equipos")
print("3. _procesar_datos_posicion() - Procesa datos por posición")
print("4. _calcular_metricas_entidad() - Calcula métricas para una entidad específica")
print("\nEstas funciones se ejecutan automáticamente dentro de calcular_comparacion_fecha_md()")
print("y no necesitan ser llamadas directamente por el usuario.")

=== FUNCIONES AUXILIARES DE PROCESAMIENTO ===
Las siguientes funciones son auxiliares internas:
1. _procesar_datos_jugadores() - Procesa datos de jugadores individuales
2. _procesar_datos_equipo() - Procesa datos de equipos
3. _procesar_datos_posicion() - Procesa datos por posición
4. _calcular_metricas_entidad() - Calcula métricas para una entidad específica

Estas funciones se ejecutan automáticamente dentro de calcular_comparacion_fecha_md()
y no necesitan ser llamadas directamente por el usuario.

## Resumen de Funciones

### Funciones Principales para el Usuario:

1. **Carga de Datos:**
   - `load_gps_data()` - Carga datos GPS
   - `get_columns_of_interest()` - Obtiene columnas de interés
   - `apply_standard_filters()` - Aplica filtros estándar

2. **Manejo de Fechas:**
   - `get_sorted_dates()` - Obtiene fechas ordenadas
   - `get_latest_date_for_picker()` - Fecha más reciente para picker
   - `format_and_filter_date()` - Filtra datos por fecha
   - `filter_and_get_players_data()` - Datos procesados de jugadores

3. **Análisis Estadístico:**
   - `calcular_estadisticas()` - Estadísticas comparativas generales
   - `calcular_comparacion_fecha_md()` - Análisis comparativo con históricos
   - `get_historical_md_data()` - Datos históricos por Match Day

4. **Procesamiento de Métricas:**
   - `add_per_minute_metrics()` - Añade métricas por minuto
   - `calcular_metricas()` - Calcula estadísticas específicas
   - `calcular_diferencia_porcentual()` - Calcula diferencias porcentuales

5. **Utilidades:**
   - `ensure_dir()` - Asegura existencia de directorios

### Funciones Auxiliares Internas:
- `_procesar_datos_jugadores()`
- `_procesar_datos_equipo()`
- `_procesar_datos_posicion()`
- `_calcular_metricas_entidad()`